---

- name: Add an Ethernet connection with static IP configuration
  community.general.nmcli:
    conn_name: "{{ iface }}"
    ifname: "{{ iface }}"
    type: ethernet
    ip4: "{{ ip_address }}/24"
    gw4: "{{ router_address }}"
    dns4: "{{ dns_address.split() }}"
    state: present
