---

- name: Add an Ethernet connection with static IP configuration
  nmcli:
    conn_name: my-eth1
    ifname: eth0
    type: ethernet
    ip4: 192.168.2.100/24
    gw4: 192.0.2.1
    state: present
