---

- name: Create keyrings directory
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Webmin GPG key
  become: yes
  ansible.builtin.shell: curl -fsSL https://download.webmin.com/jcameron-key.asc | gpg --dearmor -o /etc/apt/keyrings/webmin.gpg --yes
  args:
    creates: /etc/apt/keyrings/webmin.gpg
  tags:
    - webmin

- name: Add Webmin Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/webmin.gpg] https://download.webmin.com/download/repository sarge contrib"
    filename: webmin
  register: webmin_repo

- name: Update apt cache if repo was added
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  when: webmin_repo.changed
  tags: ['skip_ansible_lint']

- name: Ensure Webmin is installed
  become: yes
  ansible.builtin.apt:
    name: webmin
    state: present
    update_cache: yes
