---

- name: Add Webmin PGP key
  become: yes
  apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    state: present
  tags:
    - webmin

- name: Add Webmin Repository
  become: yes
  apt_repository:
    repo: "deb http://download.webmin.com/download/repository sarge contrib"
    filename: webmin
  register: webmin_repo

- name: Update apt cache if repo was added
  become: yes
  apt: update_cache=yes
  when: webmin_repo.changed
  tags: ['skip_ansible_lint']



- name: Ensure Webmin is installed
  become: yes
  apt:
    name: webmin
    state: present
    update_cache: yes
