---
- name: Download Webmin package
  ansible.builtin.get_url:
    url: 'https://prdownloads.sourceforge.net/webadmin/{{ webmin_deb_file }}'
    dest: '/tmp/{{ webmin_deb_file }}'
  when: webmin_package_check_deb.rc == 1
  tags:
    - packages
    - webmin

- name: Install webmin
  become: yes
  ansible.builtin.apt:
    deb: '/tmp/{{ webmin_deb_file }}'
  when: webmin_package_check_deb.rc == 1
  tags:
    - packages
    - webmin

- name: Clean up downloaded package
  ansible.builtin.file:
    path: '/tmp/{{ webmin_deb_file }}'
    state: absent
