---
# tasks file for indaco.lynis

- name: Install debsums package
  become: yes
  ansible.builtin.apt:
    name: debsums
    state: present

- name: Create keyrings directory
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Lynis GPG key
  become: yes
  ansible.builtin.shell: >
    curl -fsSL https://packages.cisofy.com/keys/cisofy-software-public.key |
    gpg --dearmor -o /etc/apt/keyrings/cisofy-lynis.gpg --yes
  args:
    creates: /etc/apt/keyrings/cisofy-lynis.gpg

- name: Install the https method for APT
  become: yes
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Configure APT to skip downloading translations if use software in english
  become: yes
  ansible.builtin.copy:
    content: 'Acquire::Languages "none";'
    dest: /etc/apt/apt.conf.d/99disable-translations
    force: no
    group: root
    owner: root
    mode: '0644'

- name: Adding the repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cisofy-lynis.gpg] https://packages.cisofy.com/community/lynis/deb/ stable main"
    state: present

- name: Refresh the local package database
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install lynis
  become: yes
  ansible.builtin.apt:
    name: lynis
    state: present

- name: Get Lynis version
  become: yes
  ansible.builtin.command: lynis show version
  register: lynis_version
  changed_when: false

- name: Show Lynis version
  ansible.builtin.debug:
    msg: "Lynis version is: {{ lynis_version.stdout }}"
