---
# tasks file for roles/indaco.docker

- name: Install prerequisites
  become: yes
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Create keyrings directory
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  become: yes
  ansible.builtin.shell: curl -fsSL {{ docker_apt_gpg_key }} | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Set permissions on Docker GPG key
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    update_cache: true

- name: Install Docker
  become: yes
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add ansible_user to "docker" group
  become: yes
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: 'docker'
    append: yes
  tags:
    - docker

- name: Run and enable docker
  become: yes
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Run and enable containerd
  become: yes
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes

- name: Install docker Python library
  become: yes
  ansible.builtin.pip:
    name: docker
    state: present
