---
# handlers file for roles/exim

- name: update exim4.conf.template
  become: yes
  command: update-exim4.conf.template -r
  notify: update exim4.conf

- name: update exim4.conf
  become: yes
  command: /usr/sbin/update-exim4.conf
  notify: reload exim4

- name: reload exim4
  become: yes
  service: name=exim4 state=reloaded

- name: restart exim4
  become: yes
  service: name=exim4 state=restarted

- name: newaliases
  become: yes
  command: /usr/bin/newaliases
