---

# handlers file for ansible-sshd
- name: Restart ssh
  become: yes
  service:
    name: ssh
    state: restarted

- name: Reboot host and wait for it to restart
  become: yes
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
