---
# tasks file for roles/nodejs_yarn_pm2

- name: Ensure dependencies are installed
  become: yes
  apt:
    name:
      - gcc
      - g++
      - make
      - apt-transport-https
      - gnupg2
    state: present

## NodeJS
- name: Add Nodesource apt key.
  become: yes
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for NodeJS
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present
  register: node_repo

- name: Update apt cache if repo was added
  become: yes
  apt: update_cache=yes
  when: node_repo.changed
  tags: ['skip_ansible_lint']

- name: Ensure Node.js and npm are installed.
  become: yes
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present

## Yarn
#- name: Add Yarn apt key
#  become: yes
#  apt_key:
#    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  become: yes
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn
  register: yarn_repo

- name: Update apt cache if repo was added
  become: yes
  apt: update_cache=yes
  when: yarn_repo.changed
  tags: ['skip_ansible_lint']

- name: Install Yarn
  become: yes
  apt:
    name: yarn
    state: present

## PM2
- name: Install PM2 Globally
  become: yes
  yarn:
    name: pm2
    version: "{{ pm2_version }}"
    global: yes
    state: latest

- name: Generate a startup script for PM2
  become: yes
  command: "pm2 startup systemd -u {{ ansible_user }} --hp /home/{{ansible_user}}"
  environment:
    PATH: "{{ ansible_env.PATH }}"
