---
# tasks file for roles/firewall

- name: Install UFW
  become: yes
  ansible.builtin.apt:
    name:
      - ufw
    state: present
    autoclean: yes
  tags:
    - packages

- name: Set default incoming policy
  become: yes
  community.general.ufw:
    direction: incoming
    policy: "{{ firewall_default_incoming }}"
  tags:
    - firewall

- name: Set default outgoing policy
  become: yes
  community.general.ufw:
    direction: outgoing
    policy: "{{ firewall_default_outgoing }}"
  tags:
    - firewall

- name: Allow TCP ports
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    proto: tcp
  loop: "{{ firewall_allowed_tcp_ports }}"
  tags:
    - firewall

- name: Enable UFW
  become: yes
  community.general.ufw:
    state: enabled
  tags:
    - firewall

- name: Set UFW logging
  become: yes
  community.general.ufw:
    logging: "{{ firewall_logging }}"
  tags:
    - firewall

- name: Enable UFW at startup
  become: yes
  ansible.builtin.systemd:
    state: started
    name: ufw
  tags:
    - firewall
