---
# tasks file for roles/base

- name: Update apt-get repo and cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - packages

- name: Upgrade apt packages
  become: yes
  ansible.builtin.apt:
    upgrade: yes
  tags:
    - packages

- name: Upgrade all apt packages (dist)
  become: yes
  ansible.builtin.apt:
    upgrade: dist
  notify:
    - Reboot host and wait for it to restart
  tags:
    - packages
