---
# tasks file for roles/indaco.zsh

- name: Install zsh
  become: yes
  ansible.builtin.apt:
    name: zsh
    state: present
  tags:
    - packages
    - zsh

- name: Set zsh as default shell for {{ ansible_user }}
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  when: zsh_set_default_shell
  tags:
    - zsh
