---

- name: Check if OpenSSL is already installed
  ansible.builtin.stat:
    path: '/usr/src/{{ openssl_dir }}'
  register: check_openssl_dir

- name: Download and Extract OpenSSL source
  become: yes
  ansible.builtin.unarchive:
    src: '{{ openssl_download_url }}'
    dest: '/usr/src/'
    remote_src: yes
  when: not check_openssl_dir.stat.exists

- name: Run OpenSSL Configuration
  become: yes
  ansible.builtin.shell: ./config shared --prefix=/usr/local/
  args:
    chdir: '/usr/src/{{ openssl_dir }}'
  when: not check_openssl_dir.stat.exists

- name: Run OpenSSL make
  become: yes
  ansible.builtin.shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: '/usr/src/{{ openssl_dir }}'
  when: not check_openssl_dir.stat.exists

- name: Run OpenSSL make install
  become: yes
  ansible.builtin.shell: make install
  args:
    chdir: '/usr/src/{{ openssl_dir }}'
  when: not check_openssl_dir.stat.exists
