---

- name: Check if Python is already installed
  ansible.builtin.stat:
    path: '/usr/src/{{ python_dir }}'
  register: check_python_dir

- name: Download and Extract Python {{ python_version }}
  become: yes
  ansible.builtin.unarchive:
    src: '{{ python_download_url }}'
    dest: '/usr/src/'
    remote_src: yes
  when: not check_python_dir.stat.exists

- name: Run Python Configuration
  become: yes
  ansible.builtin.shell: './configure --enable-optimizations --with-openssl=/usr/src/{{ openssl_dir }}'
  args:
    chdir: '/usr/src/{{ python_dir }}'
  environment:
    LDFLAGS: -L/usr/local/lib/
    LD_LIBRARY_PATH: /usr/local/lib/
    CPPFLAGS: -I/usr/local/include -I/usr/local/include/openssl
  when: not check_python_dir.stat.exists

- name: Run Python make
  become: yes
  ansible.builtin.shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: '/usr/src/{{ python_dir }}'
  when: not check_python_dir.stat.exists

- name: Run Python altinstall
  become: yes
  ansible.builtin.shell: make altinstall
  args:
    chdir: '/usr/src/{{ python_dir }}'
  environment:
    LDFLAGS: -L/usr/local/lib/
    LD_LIBRARY_PATH: /usr/local/lib/
    CPPFLAGS: -I/usr/local/include -I/usr/local/include/openssl
  when: not check_python_dir.stat.exists
